name: mainform
description: The demo project for the wechat_assets_picker package.
version: 9.0.0+48
publish_to: none

environment:
  sdk: '>=3.1.0'
  flutter: '>=3.13.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  wechat_assets_picker:
    path: ../
  wechat_camera_picker: ^4.0.0

  extended_image: ^8.1.0
  package_info_plus: ^4.0.0
  path: ^1.8.0
  path_provider: ^2.0.15
  provider: ^6.0.2
  redux_epics: ^0.15.1
  logger: ^2.0.2+1
  flutter_redux: ^0.10.0
  pdf: ^3.10.7

dev_dependencies:
  flutter_lints: any

flutter:
  uses-material-design: true
  assets:
    - assets/
